#!/bin/bash
[ -e /src/arduino-1.8.5/arduino ] && /src/arduino-1.8.5/arduino --upload --board adafruit:samd:adafruit_feather_m0 --port /dev/ttyACM0 -v midi-ble-menu-m0.ino 
[ -e ~/arduino-1.8.9/arduino ] && ~/arduino-1.8.9/arduino --upload --board adafruit:samd:adafruit_feather_m0 --port /dev/ttyACM0 -v midi-ble-menu-m0.ino 
